import Head from 'next/head'
import Hero from '../components/Hero'
import Instagram from '../components/Instagram'
import Slider from '../components/Slider'
import Footer from '../components/Footer'
import { SliderData } from '../components/SliderData'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
       <link rel='icon' href='/favicon.ico'/>
      </Head>
      <Hero heading=" DISCOVER STORY / worthy travel moments"
      message=" Explore this year’s expert-approved list of must-see destinations, places, and unforgettable experiences guaranteed to inspire."/>
      <Slider slides={SliderData} />
      <Instagram/>
      <Footer/>
    </div>
  );
}
